name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: 
        docker build . --file Dockerfile -tag ${{secrets.DOCKER_USERNAME}}/django_webapp:v1.0
        docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_PASSWORD}}
        docker push ${{secrets.DOCKER_USERNAME}}/django_webapp:v1.0
      
